Fix java.lang.NoSuchMethodError
Accessing different files, even in the same package, throws a `java.lang.NoSuchMethodError`. So, put everything that was in separate files in one file. This needs to be resolved in the future.