Implementing casa-processor (#552)
* casa-processor implementation

* Add casa support to sugar-processor

* Remove the Android dependency on the casa-processor module

* Remove the project dependencies on the casa-processor module

* Code cleanup

- Make spotless happy
- Remove useless plugin

* Fix java.lang.NoSuchMethodError

Accessing different files, even in the same package, throws a `java.lang.NoSuchMethodError`. So, put everything that was in separate files in one file. This needs to be resolved in the future.

* Create java.lang.NoSuchMethodError note

* Fix casa-processor implementation

* Set @CasaValue for quack components

* Project rebuild

* Uses casaModels

* Make spotless happy

* Fix sugar-processor test